package xyz.qwewqa.relive.simulator.core.stage.common

val skillIcons =
    mapOf(
        1 to listOf("attack", "atk", "hit", "slap"),
        2 to listOf("attack", "atk", "hit", "slap"),
        3 to listOf("attack", "atk", "hit", "slap"),
        5 to listOf("attack", "atk", "hit", "slap"),
        6 to listOf("heal", "healing", "recover", "recovery"),
        8 to listOf("atk up", "act up", "act power up", "power up"),
        9 to listOf("atk down", "act down", "act power down", "power down"),
        10 to
            listOf(
                "norm def up",
                "normal defense up",
                "pdef up",
                "physical defense up",
                "normal defence up",
                "pdefence up",
                "physical defence up"),
        11 to
            listOf(
                "norm def down",
                "normal defense down",
                "pdef down",
                "physical defense down",
                "normal defence down",
                "pdefence down",
                "physical defence down"),
        12 to
            listOf(
                "spec def up",
                "special defense up",
                "mdef up",
                "magic defense up",
                "special defence up",
                "mdefence up",
                "magic defence up"),
        13 to
            listOf(
                "spec def down",
                "special defense down",
                "mdef down",
                "magic defense down",
                "special defence down",
                "mdefence down",
                "magic defence down"),
        14 to listOf("agi up", "agility up", "speed up"),
        15 to listOf("agi down", "agility down", "speed down"),
        16 to listOf("acc up", "accuracy up", "hit rate up"),
        17 to listOf("acc down", "accuracy down", "hit rate down"),
        18 to listOf("eva up", "evasion up", "dodge up"),
        19 to listOf("eva down", "evasion down", "dodge down"),
        20 to listOf("dex up", "dexterity up"),
        21 to listOf("dex down", "dexterity down"),
        22 to listOf("crit up", "critical up", "crit rate up"),
        23 to listOf("crit down", "critical down", "crit rate down"),
        24 to listOf("max hp up", "max health up"),
        25 to listOf("max hp down", "max health down"),
        26 to listOf("ner", "negative effect resistance up"),
        27 to listOf("ner down", "negative effect resistance down"),
        28 to listOf("hp regen", "health regen", "hp recovery", "health recovery"),
        29 to listOf("kira regen", "kira recovery", "brilliance regen", "brilliance recovery"),
        30 to listOf("normal barrier", "norm barrier", "pbarr", "physical barrier"),
        31 to listOf("special barrier", "spec barrier", "mbarr", "magic barrier"),
        32 to listOf("normal reflect", "norm reflect", "prefl", "physical reflect"),
        33 to listOf("special reflect", "spec reflect", "mrefl", "magic reflect"),
        34 to listOf("evasion", "evade", "dodge"),
        35 to listOf("perfect aim", "paim"),
        36 to listOf("fortitude", "fort", "guts"),
        39 to
            listOf(
                "eff up",
                "eff dmg",
                "eff ele dmg",
                "effective up",
                "effective damage up",
                "effective elemental damage up"),
        40 to
            listOf("cx up", "cx dmg up", "ca up", "ca damage up", "climax up", "climax damage up"),
        41 to listOf("attack", "atk", "hit", "slap"),
        44 to listOf("absorb", "hp drain", "hp absorb", "hp sap"),
        45 to listOf("counter heal", "cheal"),
        54 to listOf("poison", "poisoning"),
        55 to listOf("burn", "burning"),
        56 to listOf("provoke"),
        57 to listOf("stun"),
        58 to listOf("sleep"),
        59 to listOf("confuse", "confusion"),
        60 to listOf("stop"),
        61 to listOf("freeze"),
        62 to listOf("blind", "blindness"),
        65 to listOf("hp recovery down", "hp gain down"),
        66 to listOf("flower bulk", "flower bulk", "flower bulk"),
        67 to listOf("wind bulk", "wind bulk", "wind bulk"),
        68 to listOf("snow bulk", "snow bulk", "snow bulk"),
        69 to listOf("moon bulk", "moon bulk", "moon bulk"),
        70 to listOf("space bulk", "space bulk", "space bulk"),
        71 to listOf("cloud bulk", "cloud bulk", "cloud bulk"),
        72 to listOf("dream bulk", "dream bulk", "dream bulk"),
        73 to listOf("flower act", "flower atk"),
        74 to listOf("wind act", "wind atk"),
        75 to listOf("snow act", "snow atk"),
        76 to listOf("moon act", "moon atk"),
        77 to listOf("space act", "space atk"),
        78 to listOf("cloud act", "cloud atk"),
        79 to listOf("dream act", "dream atk"),
        89 to listOf("brilliance recovery", "kira recovery"),
        91 to listOf("poison resistance"),
        92 to listOf("burn resistance"),
        93 to listOf("provoke resistance"),
        94 to listOf("stun resistance"),
        95 to listOf("sleep resistance"),
        96 to listOf("confuse resistance"),
        97 to listOf("stop resistance"),
        98 to listOf("freeze resistance"),
        99 to listOf("blind resistance"),
        100 to listOf("hp recovery down resistance", "hp gain down resistance"),
        111 to listOf("dmg up", "damage up"),
        114 to
            listOf(
                "dmg down",
                "damage down",
                "dmg taken down",
                "damage taken down",
                "dmg received down",
                "damage received down",
                "dmg reduction",
                "damage reduction"),
        140 to listOf("act change"),
        141 to listOf("act change remove"),
        150 to listOf("mark"),
        151 to listOf("flip"),
        152 to listOf("aggro"),
        153 to listOf("aggro resistance"),
        155 to listOf("exit evasion", "exit evade"),
        156 to listOf("invincibility", "invincible", "invulnerability", "invulnerable"),
        157 to listOf("ap down"),
        173 to listOf("ap up"),
        174 to listOf("all resistance", "all effect resistance"),
        175 to listOf("mark resistance"),
        178 to listOf("act seal", "act lock"),
        192 to
            listOf(
                "dim",
                "brilliance gain down",
                "kira gain down",
                "brilliance recovery down",
                "kira recovery down"),
        197 to listOf("revive", "revival"),
        198 to listOf("attack", "atk", "hit", "slap"),
        220 to
            listOf("cx down", "cx dmg down", "ca down", "ca damage down", "climax down", "climax damage down"),
        221 to listOf("lovesickness", "love sickness", "love sick", "love sick"),
        222 to listOf("kira drain", "brilliance drain"),
        223 to listOf("max hp up", "max health up"),
        224 to listOf("max hp down", "max health down"),
        227 to listOf("electric shock", "shocked"),
        228 to listOf("revive", "revival"),
        234 to listOf("nightmare"),
        235 to listOf("per", "positive effect resistance up"),
        236 to listOf("daze"),
        237 to listOf("impudence", "pride"),
        238 to listOf("hope"),
        240 to listOf("weak spot"),
        241 to listOf("frostbite", "frost bite", "frostbitten", "frost bitten"),
        242 to listOf("agony", "agonized"),
        243 to listOf("multiple cafication", "multiple ca fication", "multica", "multicx", "multi ca", "multi cx"),
        244 to listOf("ap up resistance"),

    )
