package xyz.qwewqa.relive.simulator.core.presets.dress

import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13EmperorAkira
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13EmperorAkiraDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13EmperorAkiraDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13EmperorAkiraStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13KomachiTamao
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13KomachiTamaoDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13KomachiTamaoDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13KomachiTamaoStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13SetsunaIchie
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13SetsunaIchieDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13SetsunaIchieDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13SetsunaIchieStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13SuirenYuyuko
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13SuirenYuyukoDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13SuirenYuyukoDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.tr13SuirenYuyukoStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14EmperorAkira
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14EmperorAkiraDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14EmperorAkiraDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14EmperorAkiraStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14MusketeerHikari
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14MusketeerHikariDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14MusketeerHikariDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14MusketeerHikariStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14MusketeerKaren
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14MusketeerKarenDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14MusketeerKarenDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14MusketeerKarenStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14MusketeerMahiru
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14MusketeerMahiruDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14MusketeerMahiruDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.tr14MusketeerMahiruStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15CheerAkira
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15CheerAkiraDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15CheerAkiraDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15CheerAkiraStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15CheerTsukasa
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15CheerTsukasaDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15CheerTsukasaDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15CheerTsukasaStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15CheerYachiyo
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15CheerYachiyoDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15CheerYachiyoDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15CheerYachiyoStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15TowerHikari
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15TowerHikariDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15TowerHikariDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.tr15TowerHikariStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16BuggedHangedManRui
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16BuggedHangedManRuiStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16HangedManRui
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16HangedManRuiDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16HangedManRuiDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16HangedManRuiStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16MafiaKaoruko
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16MafiaKaorukoDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16MafiaKaorukoDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16MafiaKaorukoStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16MafiaMaya
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16MafiaMayaDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16MafiaMayaDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16MafiaMayaStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16MafiaNana
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16MafiaNanaDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16MafiaNanaDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.tr16MafiaNanaStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17DraculaClaudine
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17DraculaClaudineDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17DraculaClaudineDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17DraculaClaudineStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17FaithMisora
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17FaithMisoraDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17FaithMisoraDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17FaithMisoraStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17HellsingMichiru
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17HellsingMichiruDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17HellsingMichiruDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17HellsingMichiruStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17VampireShiori
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17VampireShioriDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17VampireShioriDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.tr17VampireShioriStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18AliceAruru
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18AliceAruruDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18AliceAruruDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18AliceAruruStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18EmperorAkira
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18EmperorAkiraDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18EmperorAkiraDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18EmperorAkiraStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18QueenOfHeartsShizuha
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18QueenOfHeartsShizuhaDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18QueenOfHeartsShizuhaDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18QueenOfHeartsShizuhaStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18WhiteRabbitMisora
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18WhiteRabbitMisoraDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18WhiteRabbitMisoraDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.tr18WhiteRabbitMisoraStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19KomachiTamao
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19KomachiTamaoDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19KomachiTamaoDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19KomachiTamaoStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19SetsunaIchie
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19SetsunaIchieDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19SetsunaIchieDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19SetsunaIchieStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19SuirenYuyuko
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19SuirenYuyukoDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19SuirenYuyukoDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19SuirenYuyukoStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19TowerHikari
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19TowerHikariDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19TowerHikariDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.tr19TowerHikariStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20HangedManRui
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20HangedManRuiDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20HangedManRuiDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20HangedManRuiStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20MusketeerHikari
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20MusketeerHikariDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20MusketeerHikariDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20MusketeerHikariStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20MusketeerKaren
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20MusketeerKarenDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20MusketeerKarenDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20MusketeerKarenStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20MusketeerMahiru
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20MusketeerMahiruDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20MusketeerMahiruDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.tr20MusketeerMahiruStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21CheerAkira
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21CheerAkiraDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21CheerAkiraDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21CheerAkiraStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21CheerTsukasa
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21CheerTsukasaDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21CheerTsukasaDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21CheerTsukasaStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21CheerYachiyo
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21CheerYachiyoDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21CheerYachiyoDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21CheerYachiyoStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21TowerHikari
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21TowerHikariDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21TowerHikariDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.tr21TowerHikariStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22DraculaClaudine
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22DraculaClaudineDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22DraculaClaudineDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22DraculaClaudineStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22FaithMisora
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22FaithMisoraDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22FaithMisoraDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22FaithMisoraStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22HellsingMichiru
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22HellsingMichiruDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22HellsingMichiruDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22HellsingMichiruStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22VampireShiori
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22VampireShioriDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22VampireShioriDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.tr22VampireShioriStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23EmperorAkira
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23EmperorAkiraDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23EmperorAkiraDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23EmperorAkiraStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23MafiaKaoruko
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23MafiaKaorukoDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23MafiaKaorukoDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23MafiaKaorukoStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23MafiaMaya
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23MafiaMayaDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23MafiaMayaDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23MafiaMayaStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23MafiaNana
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23MafiaNanaDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23MafiaNanaDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.tr23MafiaNanaStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24AliceAruru
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24AliceAruruDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24AliceAruruDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24AliceAruruStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24HangedManRui
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24HangedManRuiDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24HangedManRuiDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24HangedManRuiStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24QueenOfHeartsShizuha
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24QueenOfHeartsShizuhaDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24QueenOfHeartsShizuhaDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24QueenOfHeartsShizuhaStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24WhiteRabbitMisora
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24WhiteRabbitMisoraDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24WhiteRabbitMisoraDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.tr24WhiteRabbitMisoraStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25FaithMisora
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25FaithMisoraDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25FaithMisoraDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25FaithMisoraStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25KomachiTamao
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25KomachiTamaoDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25KomachiTamaoDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25KomachiTamaoStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25SetsunaIchie
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25SetsunaIchieDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25SetsunaIchieDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25SetsunaIchieStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25SuirenYuyuko
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25SuirenYuyukoDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25SuirenYuyukoDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.tr25SuirenYuyukoStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26EmperorAkira
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26EmperorAkiraDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26EmperorAkiraDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26EmperorAkiraDiff4Ver2023
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26EmperorAkiraStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26EmperorAkiraVer2023
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerHikari
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerHikariDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerHikariDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerHikariDiff4Ver2023
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerHikariStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerHikariVer2023
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerKaren
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerKarenDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerKarenDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerKarenDiff4Ver2023
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerKarenStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerKarenVer2023
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerMahiru
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerMahiruDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerMahiruDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerMahiruDiff4Ver2023
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerMahiruStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.tr26MusketeerMahiruVer2023
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27MafiaKaoruko
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27MafiaKaorukoDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27MafiaKaorukoDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27MafiaKaorukoStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27MafiaMaya
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27MafiaMayaDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27MafiaMayaDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27MafiaMayaStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27MafiaNana
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27MafiaNanaDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27MafiaNanaDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27MafiaNanaStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27TowerHikari
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27TowerHikariDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27TowerHikariDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr27.tr27TowerHikariStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28DraculaClaudine
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28DraculaClaudineDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28DraculaClaudineDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28DraculaClaudineStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28HangedManRui
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28HangedManRuiDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28HangedManRuiDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28HangedManRuiStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28HellsingMichiru
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28HellsingMichiruDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28HellsingMichiruDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28HellsingMichiruStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28VampireShiori
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28VampireShioriDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28VampireShioriDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr28.tr28VampireShioriStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29CheerAkira
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29CheerAkiraDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29CheerAkiraDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29CheerAkiraStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29CheerTsukasa
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29CheerTsukasaDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29CheerTsukasaDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29CheerTsukasaStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29CheerYachiyo
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29CheerYachiyoDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29CheerYachiyoDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29CheerYachiyoStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29FaithMisora
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29FaithMisoraDiff4
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29FaithMisoraDiff4Strategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr29.tr29FaithMisoraStrategy
import xyz.qwewqa.relive.simulator.core.stage.loadout.ActorLoadout
import xyz.qwewqa.relive.simulator.core.stage.strategy.Strategy

data class BossLoadout(val loadout: ActorLoadout, val strategy: Strategy)

val bossLoadouts =
    listOf(
        BossLoadout(tr29CheerAkira, tr29CheerAkiraStrategy),
        BossLoadout(tr29CheerAkiraDiff4, tr29CheerAkiraDiff4Strategy),
        BossLoadout(tr29CheerTsukasa, tr29CheerTsukasaStrategy),
        BossLoadout(tr29CheerTsukasaDiff4, tr29CheerTsukasaDiff4Strategy),
        BossLoadout(tr29CheerYachiyo, tr29CheerYachiyoStrategy),
        BossLoadout(tr29CheerYachiyoDiff4, tr29CheerYachiyoDiff4Strategy),
        BossLoadout(tr29FaithMisora, tr29FaithMisoraStrategy),
        BossLoadout(tr29FaithMisoraDiff4, tr29FaithMisoraDiff4Strategy),
        BossLoadout(tr28DraculaClaudine, tr28DraculaClaudineStrategy),
        BossLoadout(tr28DraculaClaudineDiff4, tr28DraculaClaudineDiff4Strategy),
        BossLoadout(tr28VampireShiori, tr28VampireShioriStrategy),
        BossLoadout(tr28VampireShioriDiff4, tr28VampireShioriDiff4Strategy),
        BossLoadout(tr28HellsingMichiru, tr28HellsingMichiruStrategy),
        BossLoadout(tr28HellsingMichiruDiff4, tr28HellsingMichiruDiff4Strategy),
        BossLoadout(tr28HangedManRui, tr28HangedManRuiStrategy),
        BossLoadout(tr28HangedManRuiDiff4, tr28HangedManRuiDiff4Strategy),
        BossLoadout(tr27MafiaNana, tr27MafiaNanaStrategy),
        BossLoadout(tr27MafiaNanaDiff4, tr27MafiaNanaDiff4Strategy),
        BossLoadout(tr27MafiaMaya, tr27MafiaMayaStrategy),
        BossLoadout(tr27MafiaMayaDiff4, tr27MafiaMayaDiff4Strategy),
        BossLoadout(tr27MafiaKaoruko, tr27MafiaKaorukoStrategy),
        BossLoadout(tr27MafiaKaorukoDiff4, tr27MafiaKaorukoDiff4Strategy),
        BossLoadout(tr27TowerHikari, tr27TowerHikariStrategy),
        BossLoadout(tr27TowerHikariDiff4, tr27TowerHikariDiff4Strategy),
        BossLoadout(tr26MusketeerKarenVer2023, tr26MusketeerKarenStrategy),
        BossLoadout(tr26MusketeerKarenDiff4Ver2023, tr26MusketeerKarenDiff4Strategy),
        BossLoadout(tr26MusketeerHikariVer2023, tr26MusketeerHikariStrategy),
        BossLoadout(tr26MusketeerHikariDiff4Ver2023, tr26MusketeerHikariDiff4Strategy),
        BossLoadout(tr26MusketeerMahiruVer2023, tr26MusketeerMahiruStrategy),
        BossLoadout(tr26MusketeerMahiruDiff4Ver2023, tr26MusketeerMahiruDiff4Strategy),
        BossLoadout(tr26EmperorAkiraVer2023, tr26EmperorAkiraStrategy),
        BossLoadout(tr26EmperorAkiraDiff4Ver2023, tr26EmperorAkiraDiff4Strategy),
        BossLoadout(tr26MusketeerKaren, tr26MusketeerKarenStrategy),
        BossLoadout(tr26MusketeerKarenDiff4, tr26MusketeerKarenDiff4Strategy),
        BossLoadout(tr26MusketeerHikari, tr26MusketeerHikariStrategy),
        BossLoadout(tr26MusketeerHikariDiff4, tr26MusketeerHikariDiff4Strategy),
        BossLoadout(tr26MusketeerMahiru, tr26MusketeerMahiruStrategy),
        BossLoadout(tr26MusketeerMahiruDiff4, tr26MusketeerMahiruDiff4Strategy),
        BossLoadout(tr26EmperorAkira, tr26EmperorAkiraStrategy),
        BossLoadout(tr26EmperorAkiraDiff4, tr26EmperorAkiraDiff4Strategy),
        BossLoadout(tr25SetsunaIchie, tr25SetsunaIchieStrategy),
        BossLoadout(tr25SetsunaIchieDiff4, tr25SetsunaIchieDiff4Strategy),
        BossLoadout(tr25SuirenYuyuko, tr25SuirenYuyukoStrategy),
        BossLoadout(tr25SuirenYuyukoDiff4, tr25SuirenYuyukoDiff4Strategy),
        BossLoadout(tr25KomachiTamao, tr25KomachiTamaoStrategy),
        BossLoadout(tr25KomachiTamaoDiff4, tr25KomachiTamaoDiff4Strategy),
        BossLoadout(tr25FaithMisora, tr25FaithMisoraStrategy),
        BossLoadout(tr25FaithMisoraDiff4, tr25FaithMisoraDiff4Strategy),
        BossLoadout(tr24WhiteRabbitMisora, tr24WhiteRabbitMisoraStrategy),
        BossLoadout(tr24WhiteRabbitMisoraDiff4, tr24WhiteRabbitMisoraDiff4Strategy),
        BossLoadout(tr24AliceAruru, tr24AliceAruruStrategy),
        BossLoadout(tr24AliceAruruDiff4, tr24AliceAruruDiff4Strategy),
        BossLoadout(tr24QueenOfHeartsShizuha, tr24QueenOfHeartsShizuhaStrategy),
        BossLoadout(tr24QueenOfHeartsShizuhaDiff4, tr24QueenOfHeartsShizuhaDiff4Strategy),
        BossLoadout(tr24HangedManRui, tr24HangedManRuiStrategy),
        BossLoadout(tr24HangedManRuiDiff4, tr24HangedManRuiDiff4Strategy),
        BossLoadout(tr23MafiaNana, tr23MafiaNanaStrategy),
        BossLoadout(tr23MafiaNanaDiff4, tr23MafiaNanaDiff4Strategy),
        BossLoadout(tr23MafiaMaya, tr23MafiaMayaStrategy),
        BossLoadout(tr23MafiaMayaDiff4, tr23MafiaMayaDiff4Strategy),
        BossLoadout(tr23MafiaKaoruko, tr23MafiaKaorukoStrategy),
        BossLoadout(tr23MafiaKaorukoDiff4, tr23MafiaKaorukoDiff4Strategy),
        BossLoadout(tr23EmperorAkira, tr23EmperorAkiraStrategy),
        BossLoadout(tr23EmperorAkiraDiff4, tr23EmperorAkiraDiff4Strategy),
        BossLoadout(tr22DraculaClaudine, tr22DraculaClaudineStrategy),
        BossLoadout(tr22DraculaClaudineDiff4, tr22DraculaClaudineDiff4Strategy),
        BossLoadout(tr22VampireShiori, tr22VampireShioriStrategy),
        BossLoadout(tr22VampireShioriDiff4, tr22VampireShioriDiff4Strategy),
        BossLoadout(tr22HellsingMichiru, tr22HellsingMichiruStrategy),
        BossLoadout(tr22HellsingMichiruDiff4, tr22HellsingMichiruDiff4Strategy),
        BossLoadout(tr22FaithMisora, tr22FaithMisoraStrategy),
        BossLoadout(tr22FaithMisoraDiff4, tr22FaithMisoraDiff4Strategy),
        BossLoadout(tr21CheerAkira, tr21CheerAkiraStrategy),
        BossLoadout(tr21CheerAkiraDiff4, tr21CheerAkiraDiff4Strategy),
        BossLoadout(tr21CheerTsukasa, tr21CheerTsukasaStrategy),
        BossLoadout(tr21CheerTsukasaDiff4, tr21CheerTsukasaDiff4Strategy),
        BossLoadout(tr21CheerYachiyo, tr21CheerYachiyoStrategy),
        BossLoadout(tr21CheerYachiyoDiff4, tr21CheerYachiyoDiff4Strategy),
        BossLoadout(tr21TowerHikari, tr21TowerHikariStrategy),
        BossLoadout(tr21TowerHikariDiff4, tr21TowerHikariDiff4Strategy),
        BossLoadout(tr20MusketeerKaren, tr20MusketeerKarenStrategy),
        BossLoadout(tr20MusketeerKarenDiff4, tr20MusketeerKarenDiff4Strategy),
        BossLoadout(tr20MusketeerHikari, tr20MusketeerHikariStrategy),
        BossLoadout(tr20MusketeerHikariDiff4, tr20MusketeerHikariDiff4Strategy),
        BossLoadout(tr20MusketeerMahiru, tr20MusketeerMahiruStrategy),
        BossLoadout(tr20MusketeerMahiruDiff4, tr20MusketeerMahiruDiff4Strategy),
        BossLoadout(tr20HangedManRui, tr20HangedManRuiStrategy),
        BossLoadout(tr20HangedManRuiDiff4, tr20HangedManRuiDiff4Strategy),
        BossLoadout(tr19SetsunaIchie, tr19SetsunaIchieStrategy),
        BossLoadout(tr19SetsunaIchieDiff4, tr19SetsunaIchieDiff4Strategy),
        BossLoadout(tr19SuirenYuyuko, tr19SuirenYuyukoStrategy),
        BossLoadout(tr19SuirenYuyukoDiff4, tr19SuirenYuyukoDiff4Strategy),
        BossLoadout(tr19KomachiTamao, tr19KomachiTamaoStrategy),
        BossLoadout(tr19KomachiTamaoDiff4, tr19KomachiTamaoDiff4Strategy),
        BossLoadout(tr19TowerHikari, tr19TowerHikariStrategy),
        BossLoadout(tr19TowerHikariDiff4, tr19TowerHikariDiff4Strategy),
        BossLoadout(tr18WhiteRabbitMisora, tr18WhiteRabbitMisoraStrategy),
        BossLoadout(tr18WhiteRabbitMisoraDiff4, tr18WhiteRabbitMisoraDiff4Strategy),
        BossLoadout(tr18AliceAruru, tr18AliceAruruStrategy),
        BossLoadout(tr18AliceAruruDiff4, tr18AliceAruruDiff4Strategy),
        BossLoadout(tr18QueenOfHeartsShizuha, tr18QueenOfHeartsShizuhaStrategy),
        BossLoadout(tr18QueenOfHeartsShizuhaDiff4, tr18QueenOfHeartsShizuhaDiff4Strategy),
        BossLoadout(tr18EmperorAkira, tr18EmperorAkiraStrategy),
        BossLoadout(tr18EmperorAkiraDiff4, tr18EmperorAkiraDiff4Strategy),
        BossLoadout(tr17DraculaClaudine, tr17DraculaClaudineStrategy),
        BossLoadout(tr17DraculaClaudineDiff4, tr17DraculaClaudineDiff4Strategy),
        BossLoadout(tr17VampireShiori, tr17VampireShioriStrategy),
        BossLoadout(tr17VampireShioriDiff4, tr17VampireShioriDiff4Strategy),
        BossLoadout(tr17HellsingMichiru, tr17HellsingMichiruStrategy),
        BossLoadout(tr17HellsingMichiruDiff4, tr17HellsingMichiruDiff4Strategy),
        BossLoadout(tr17FaithMisora, tr17FaithMisoraStrategy),
        BossLoadout(tr17FaithMisoraDiff4, tr17FaithMisoraDiff4Strategy),
        BossLoadout(tr16MafiaNana, tr16MafiaNanaStrategy),
        BossLoadout(tr16MafiaNanaDiff4, tr16MafiaNanaDiff4Strategy),
        BossLoadout(tr16MafiaMaya, tr16MafiaMayaStrategy),
        BossLoadout(tr16MafiaMayaDiff4, tr16MafiaMayaDiff4Strategy),
        BossLoadout(tr16MafiaKaoruko, tr16MafiaKaorukoStrategy),
        BossLoadout(tr16MafiaKaorukoDiff4, tr16MafiaKaorukoDiff4Strategy),
        BossLoadout(tr16HangedManRui, tr16HangedManRuiStrategy),
        BossLoadout(tr16BuggedHangedManRui, tr16BuggedHangedManRuiStrategy),
        BossLoadout(tr16HangedManRuiDiff4, tr16HangedManRuiDiff4Strategy),
        BossLoadout(tr15CheerAkira, tr15CheerAkiraStrategy),
        BossLoadout(tr15CheerAkiraDiff4, tr15CheerAkiraDiff4Strategy),
        BossLoadout(tr15CheerTsukasa, tr15CheerTsukasaStrategy),
        BossLoadout(tr15CheerTsukasaDiff4, tr15CheerTsukasaDiff4Strategy),
        BossLoadout(tr15CheerYachiyo, tr15CheerYachiyoStrategy),
        BossLoadout(tr15CheerYachiyoDiff4, tr15CheerYachiyoDiff4Strategy),
        BossLoadout(tr15TowerHikari, tr15TowerHikariStrategy),
        BossLoadout(tr15TowerHikariDiff4, tr15TowerHikariDiff4Strategy),
        BossLoadout(tr14MusketeerKaren, tr14MusketeerKarenStrategy),
        BossLoadout(tr14MusketeerKarenDiff4, tr14MusketeerKarenDiff4Strategy),
        BossLoadout(tr14MusketeerHikari, tr14MusketeerHikariStrategy),
        BossLoadout(tr14MusketeerHikariDiff4, tr14MusketeerHikariDiff4Strategy),
        BossLoadout(tr14MusketeerMahiru, tr14MusketeerMahiruStrategy),
        BossLoadout(tr14MusketeerMahiruDiff4, tr14MusketeerMahiruDiff4Strategy),
        BossLoadout(tr14EmperorAkira, tr14EmperorAkiraStrategy),
        BossLoadout(tr14EmperorAkiraDiff4, tr14EmperorAkiraDiff4Strategy),
        BossLoadout(tr13SetsunaIchie, tr13SetsunaIchieStrategy),
        BossLoadout(tr13SetsunaIchieDiff4, tr13SetsunaIchieDiff4Strategy),
        BossLoadout(tr13SuirenYuyuko, tr13SuirenYuyukoStrategy),
        BossLoadout(tr13SuirenYuyukoDiff4, tr13SuirenYuyukoDiff4Strategy),
        BossLoadout(tr13KomachiTamao, tr13KomachiTamaoStrategy),
        BossLoadout(tr13KomachiTamaoDiff4, tr13KomachiTamaoDiff4Strategy),
        BossLoadout(tr13EmperorAkira, tr13EmperorAkiraStrategy),
        BossLoadout(tr13EmperorAkiraDiff4, tr13EmperorAkiraDiff4Strategy),
    )
        .associateBy { it.loadout.name }
