package xyz.qwewqa.relive.simulator.core.presets.dress

import xyz.qwewqa.relive.simulator.core.presets.dress.boss.seesaw.sakurataisen.sakuraTaisenStageGirlHikariBoss
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.seesaw.sakurataisen.sakuraTaisenStageGirlKarenBoss
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.seesaw.sakurataisen.sakuraTaisenStageGirlMahiruBoss
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.seesaw.seesawStrategy
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.seesaw.shinsengumirinpuden.shinsengumiRinpudenKondoIsamiIchieBoss
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.seesaw.shinsengumirinpuden.shinsengumiRinpudenNagakuraShinpachiFumiBoss
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.seesaw.shinsengumirinpuden.shinsengumiRinpudenOkitaSojiYuyukoBoss
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr10.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr11.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr12.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr13.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr14.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr15.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr16.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr17.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr18.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr19.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr20.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr21.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr22.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr23.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr24.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr25.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr26.*
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr9.tr9FaithMisora
import xyz.qwewqa.relive.simulator.core.presets.dress.boss.tr.tr9.tr9FaithMisoraStrategy
import xyz.qwewqa.relive.simulator.core.stage.loadout.ActorLoadout
import xyz.qwewqa.relive.simulator.core.stage.strategy.Strategy

data class BossLoadout(val loadout: ActorLoadout, val strategy: Strategy)

val bossLoadouts = listOf(
    BossLoadout(tr26MusketeerKaren, tr26MusketeerKarenStrategy),
    BossLoadout(tr26MusketeerKarenDiff4, tr26MusketeerKarenDiff4Strategy),
    BossLoadout(tr26MusketeerHikari, tr26MusketeerHikariStrategy),
    BossLoadout(tr26MusketeerHikariDiff4, tr26MusketeerHikariDiff4Strategy),
    BossLoadout(tr26MusketeerMahiru, tr26MusketeerMahiruStrategy),
    BossLoadout(tr26MusketeerMahiruDiff4, tr26MusketeerMahiruDiff4Strategy),
    BossLoadout(tr26HangedManRui, tr26HangedManRuiStrategy),
    BossLoadout(tr26HangedManRuiDiff4, tr26HangedManRuiDiff4Strategy),
    BossLoadout(tr25SetsunaIchie, tr25SetsunaIchieStrategy),
    BossLoadout(tr25SetsunaIchieDiff4, tr25SetsunaIchieDiff4Strategy),
    BossLoadout(tr25SuirenYuyuko, tr25SuirenYuyukoStrategy),
    BossLoadout(tr25SuirenYuyukoDiff4, tr25SuirenYuyukoDiff4Strategy),
    BossLoadout(tr25KomachiTamao, tr25KomachiTamaoStrategy),
    BossLoadout(tr25KomachiTamaoDiff4, tr25KomachiTamaoDiff4Strategy),
    BossLoadout(tr25FaithMisora, tr25FaithMisoraStrategy),
    BossLoadout(tr25FaithMisoraDiff4, tr25FaithMisoraDiff4Strategy),
    BossLoadout(tr24WhiteRabbitMisora, tr24WhiteRabbitMisoraStrategy),
    BossLoadout(tr24WhiteRabbitMisoraDiff4, tr24WhiteRabbitMisoraDiff4Strategy),
    BossLoadout(tr24AliceAruru, tr24AliceAruruStrategy),
    BossLoadout(tr24AliceAruruDiff4, tr24AliceAruruDiff4Strategy),
    BossLoadout(tr24QueenOfHeartsShizuha, tr24QueenOfHeartsShizuhaStrategy),
    BossLoadout(tr24QueenOfHeartsShizuhaDiff4, tr24QueenOfHeartsShizuhaDiff4Strategy),
    BossLoadout(tr24HangedManRui, tr24HangedManRuiStrategy),
    BossLoadout(tr24HangedManRuiDiff4, tr24HangedManRuiDiff4Strategy),
    BossLoadout(tr23MafiaNana, tr23MafiaNanaStrategy),
    BossLoadout(tr23MafiaNanaDiff4, tr23MafiaNanaDiff4Strategy),
    BossLoadout(tr23MafiaMaya, tr23MafiaMayaStrategy),
    BossLoadout(tr23MafiaMayaDiff4, tr23MafiaMayaDiff4Strategy),
    BossLoadout(tr23MafiaKaoruko, tr23MafiaKaorukoStrategy),
    BossLoadout(tr23MafiaKaorukoDiff4, tr23MafiaKaorukoDiff4Strategy),
    BossLoadout(tr23EmperorAkira, tr23EmperorAkiraStrategy),
    BossLoadout(tr23EmperorAkiraDiff4, tr23EmperorAkiraDiff4Strategy),
    BossLoadout(tr22DraculaClaudine, tr22DraculaClaudineStrategy),
    BossLoadout(tr22DraculaClaudineDiff4, tr22DraculaClaudineDiff4Strategy),
    BossLoadout(tr22VampireShiori, tr22VampireShioriStrategy),
    BossLoadout(tr22VampireShioriDiff4, tr22VampireShioriDiff4Strategy),
    BossLoadout(tr22HellsingMichiru, tr22HellsingMichiruStrategy),
    BossLoadout(tr22HellsingMichiruDiff4, tr22HellsingMichiruDiff4Strategy),
    BossLoadout(tr22FaithMisora, tr22FaithMisoraStrategy),
    BossLoadout(tr22FaithMisoraDiff4, tr22FaithMisoraDiff4Strategy),
    BossLoadout(tr21CheerAkira, tr21CheerAkiraStrategy),
    BossLoadout(tr21CheerAkiraDiff4, tr21CheerAkiraDiff4Strategy),
    BossLoadout(tr21CheerTsukasa, tr21CheerTsukasaStrategy),
    BossLoadout(tr21CheerTsukasaDiff4, tr21CheerTsukasaDiff4Strategy),
    BossLoadout(tr21CheerYachiyo, tr21CheerYachiyoStrategy),
    BossLoadout(tr21CheerYachiyoDiff4, tr21CheerYachiyoDiff4Strategy),
    BossLoadout(tr21TowerHikari, tr21TowerHikariStrategy),
    BossLoadout(tr21TowerHikariDiff4, tr21TowerHikariDiff4Strategy),
    BossLoadout(tr20MusketeerKaren, tr20MusketeerKarenStrategy),
    BossLoadout(tr20MusketeerKarenDiff4, tr20MusketeerKarenDiff4Strategy),
    BossLoadout(tr20MusketeerHikari, tr20MusketeerHikariStrategy),
    BossLoadout(tr20MusketeerHikariDiff4, tr20MusketeerHikariDiff4Strategy),
    BossLoadout(tr20MusketeerMahiru, tr20MusketeerMahiruStrategy),
    BossLoadout(tr20MusketeerMahiruDiff4, tr20MusketeerMahiruDiff4Strategy),
    BossLoadout(tr20HangedManRui, tr20HangedManRuiStrategy),
    BossLoadout(tr20HangedManRuiDiff4, tr20HangedManRuiDiff4Strategy),
    BossLoadout(tr19SetsunaIchie, tr19SetsunaIchieStrategy),
    BossLoadout(tr19SetsunaIchieDiff4, tr19SetsunaIchieDiff4Strategy),
    BossLoadout(tr19SuirenYuyuko, tr19SuirenYuyukoStrategy),
    BossLoadout(tr19SuirenYuyukoDiff4, tr19SuirenYuyukoDiff4Strategy),
    BossLoadout(tr19KomachiTamao, tr19KomachiTamaoStrategy),
    BossLoadout(tr19KomachiTamaoDiff4, tr19KomachiTamaoDiff4Strategy),
    BossLoadout(tr19TowerHikari, tr19TowerHikariStrategy),
    BossLoadout(tr19TowerHikariDiff4, tr19TowerHikariDiff4Strategy),
    BossLoadout(tr18WhiteRabbitMisora, tr18WhiteRabbitMisoraStrategy),
    BossLoadout(tr18WhiteRabbitMisoraDiff4, tr18WhiteRabbitMisoraDiff4Strategy),
    BossLoadout(tr18AliceAruru, tr18AliceAruruStrategy),
    BossLoadout(tr18AliceAruruDiff4, tr18AliceAruruDiff4Strategy),
    BossLoadout(tr18QueenOfHeartsShizuha, tr18QueenOfHeartsShizuhaStrategy),
    BossLoadout(tr18QueenOfHeartsShizuhaDiff4, tr18QueenOfHeartsShizuhaDiff4Strategy),
    BossLoadout(tr18EmperorAkira, tr18EmperorAkiraStrategy),
    BossLoadout(tr18EmperorAkiraDiff4, tr18EmperorAkiraDiff4Strategy),
    BossLoadout(tr17DraculaClaudine, tr17DraculaClaudineStrategy),
    BossLoadout(tr17DraculaClaudineDiff4, tr17DraculaClaudineDiff4Strategy),
    BossLoadout(tr17VampireShiori, tr17VampireShioriStrategy),
    BossLoadout(tr17VampireShioriDiff4, tr17VampireShioriDiff4Strategy),
    BossLoadout(tr17HellsingMichiru, tr17HellsingMichiruStrategy),
    BossLoadout(tr17HellsingMichiruDiff4, tr17HellsingMichiruDiff4Strategy),
    BossLoadout(tr17FaithMisora, tr17FaithMisoraStrategy),
    BossLoadout(tr17FaithMisoraDiff4, tr17FaithMisoraDiff4Strategy),
    BossLoadout(tr16MafiaNana, tr16MafiaNanaStrategy),
    BossLoadout(tr16MafiaNanaDiff4, tr16MafiaNanaDiff4Strategy),
    BossLoadout(tr16MafiaMaya, tr16MafiaMayaStrategy),
    BossLoadout(tr16MafiaMayaDiff4, tr16MafiaMayaDiff4Strategy),
    BossLoadout(tr16MafiaKaoruko, tr16MafiaKaorukoStrategy),
    BossLoadout(tr16MafiaKaorukoDiff4, tr16MafiaKaorukoDiff4Strategy),
    BossLoadout(tr16HangedManRui, tr16HangedManRuiStrategy),
    BossLoadout(tr16BuggedHangedManRui, tr16BuggedHangedManRuiStrategy),
    BossLoadout(tr16HangedManRuiDiff4, tr16HangedManRuiDiff4Strategy),
    BossLoadout(tr15CheerAkira, tr15CheerAkiraStrategy),
    BossLoadout(tr15CheerAkiraDiff4, tr15CheerAkiraDiff4Strategy),
    BossLoadout(tr15CheerTsukasa, tr15CheerTsukasaStrategy),
    BossLoadout(tr15CheerTsukasaDiff4, tr15CheerTsukasaDiff4Strategy),
    BossLoadout(tr15CheerYachiyo, tr15CheerYachiyoStrategy),
    BossLoadout(tr15CheerYachiyoDiff4, tr15CheerYachiyoDiff4Strategy),
    BossLoadout(tr15TowerHikari, tr15TowerHikariStrategy),
    BossLoadout(tr15TowerHikariDiff4, tr15TowerHikariDiff4Strategy),
    BossLoadout(tr14MusketeerKaren, tr14MusketeerKarenStrategy),
    BossLoadout(tr14MusketeerKarenDiff4, tr14MusketeerKarenDiff4Strategy),
    BossLoadout(tr14MusketeerHikari, tr14MusketeerHikariStrategy),
    BossLoadout(tr14MusketeerHikariDiff4, tr14MusketeerHikariDiff4Strategy),
    BossLoadout(tr14MusketeerMahiru, tr14MusketeerMahiruStrategy),
    BossLoadout(tr14MusketeerMahiruDiff4, tr14MusketeerMahiruDiff4Strategy),
    BossLoadout(tr14EmperorAkira, tr14EmperorAkiraStrategy),
    BossLoadout(tr14EmperorAkiraDiff4, tr14EmperorAkiraDiff4Strategy),
    BossLoadout(tr13SetsunaIchie, tr13SetsunaIchieStrategy),
    BossLoadout(tr13SetsunaIchieDiff4, tr13SetsunaIchieDiff4Strategy),
    BossLoadout(tr13SuirenYuyuko, tr13SuirenYuyukoStrategy),
    BossLoadout(tr13SuirenYuyukoDiff4, tr13SuirenYuyukoDiff4Strategy),
    BossLoadout(tr13KomachiTamao, tr13KomachiTamaoStrategy),
    BossLoadout(tr13KomachiTamaoDiff4, tr13KomachiTamaoDiff4Strategy),
    BossLoadout(tr13EmperorAkira, tr13EmperorAkiraStrategy),
    BossLoadout(tr13EmperorAkiraDiff4, tr13EmperorAkiraDiff4Strategy),
    BossLoadout(tr12VampireShiori, tr12VampireShioriStrategy),
    BossLoadout(tr12TowerHikari, tr12TowerHikariStrategy),
    BossLoadout(tr11CheerAkira, tr11CheerAkiraStrategy),
    BossLoadout(tr11CheerTsukasa, tr11CheerTsukasaStrategy),
    BossLoadout(tr11CheerYachiyo, tr11CheerYachiyoStrategy),
    BossLoadout(tr11FaithMisora, tr11FaithMisoraStrategy),
    BossLoadout(tr10DraculaClaudine, tr10DraculaClaudineStrategy),
    BossLoadout(tr10VampireShiori, tr10VampireShioriStrategy),
    BossLoadout(tr10HellsingMichiru, tr10HellsingMichiruStrategy),
    BossLoadout(tr10FaithMisora, tr10FaithMisoraStrategy),
    BossLoadout(tr9FaithMisora, tr9FaithMisoraStrategy),
    BossLoadout(sakuraTaisenStageGirlKarenBoss, seesawStrategy),
    BossLoadout(sakuraTaisenStageGirlHikariBoss, seesawStrategy),
    BossLoadout(sakuraTaisenStageGirlMahiruBoss, seesawStrategy),
    BossLoadout(shinsengumiRinpudenKondoIsamiIchieBoss, seesawStrategy),
    BossLoadout(shinsengumiRinpudenNagakuraShinpachiFumiBoss, seesawStrategy),
    BossLoadout(shinsengumiRinpudenOkitaSojiYuyukoBoss, seesawStrategy),
).associateBy { it.loadout.name }
