package xyz.qwewqa.relive.simulator.core.presets.dress

import xyz.qwewqa.relive.simulator.core.presets.dress.back.cloud.*
import xyz.qwewqa.relive.simulator.core.presets.dress.back.flower.*
import xyz.qwewqa.relive.simulator.core.presets.dress.back.moon.*
import xyz.qwewqa.relive.simulator.core.presets.dress.back.snow.*
import xyz.qwewqa.relive.simulator.core.presets.dress.back.space.*
import xyz.qwewqa.relive.simulator.core.presets.dress.back.wind.*
import xyz.qwewqa.relive.simulator.core.presets.dress.front.cloud.EmpressMeiFan
import xyz.qwewqa.relive.simulator.core.presets.dress.front.flower.EmperorAkira
import xyz.qwewqa.relive.simulator.core.presets.dress.front.moon.FaithMisora
import xyz.qwewqa.relive.simulator.core.presets.dress.front.snow.*
import xyz.qwewqa.relive.simulator.core.presets.dress.front.space.CharityTsukasa
import xyz.qwewqa.relive.simulator.core.presets.dress.front.wind.StrengthFutaba
import xyz.qwewqa.relive.simulator.core.presets.dress.middle.cloud.*
import xyz.qwewqa.relive.simulator.core.presets.dress.middle.flower.*
import xyz.qwewqa.relive.simulator.core.presets.dress.middle.snow.*
import xyz.qwewqa.relive.simulator.core.presets.dress.middle.moon.*
import xyz.qwewqa.relive.simulator.core.presets.dress.middle.space.*
import xyz.qwewqa.relive.simulator.core.presets.dress.middle.wind.*
import xyz.qwewqa.relive.simulator.core.presets.dress.middle.star.SiegfriedNana
import xyz.qwewqa.relive.simulator.core.presets.dress.back.dream.WhiteFrontierAruru

val playerDresses = listOf(
    AceMisora,
    AnastasiaJunna,
    BlackShizuha,
    BloodyDevilShiori,
    BlueFrontierMisora,
    CatalinaKaoruko,
    CerberusIchie,
    ChariotShiori,
    CharityTsukasa,
    CollectionKaoruko,
    CollectionYachiyo,
    CompetitionRevueMahiru,
    CourtChampionYachiyo,
    CoyoteCainYachiyo,
    DancerClaudine,
    DeathTamao,
    DelightAkira,
    DelightMichiru,
    DemonKingNana,
    DevilKaoruko,
    DonJoseFumi,
    EmperorAkira,
    EmpressMeiFan,
    EurydiceYuyuko,
    FaithMisora,
    FinalLinesHikari,
    FinalLinesKaren,
    FoolYachiyo,
    FuMeiFan,
    FutureStageGirlKuina,
    FutureStageGirlShiro,
    FutureStageGirlStella,
    GrudgeRevueFutaba,
    GrudgeRevueKaoruko,
    HadesRui,
    HelldiverNana,
    HeroHikari,
    HierophantMichiru,
    HijikataToshizoTamao,
    HondaFutaba,
    HopeLalafin,
    HuntingRevueJunna,
    HuntingRevueNana,
    ImperialCombatRevueFlowerDivisionSakura,
    IzanagiNana,
    JoshuaMichiru,
    JudgementShizuha,
    JulietShiori,
    JusticeNana,
    KondoIsamiIchie,
    LittlePrinceMisora,
    LokiYachiyo,
    MagicianYuyuko,
    MerchantKaoruko,
    MitsuhideKaren,
    MoonAruru,
    MurasakiKaoruko,
    NagakuraShinpachiFumi,
    NewYorkCombatRevueGemie,
    OfficerKaren,
    OfficerIchie,
    OfficerRui,
    OkuninushiKaren,
    OrpheusFumi,
    ParisCombatRevueFlowerDivisionErika,
    PersephoneTamao,
    PrincessKaren,
    RedFrontierLalafin,
    RomeoKaren,
    SageJunna,
    SakataNoKintokiMeiFan,
    SakuraShingujiHikari,
    SakuyahimeMahiru,
    SanadaMahiru,
    SeimeiMichiru,
    ShutendojiShiori,
    SiegfriedNana,
    SleepingBeautyHikari,
    SnowWhiteKoharu,
    SnowWhitePrinceSuzu,
    SonokoYachiyo,
    SorcererMahiru,
    SoulRevueClaudine,
    SoulRevueMaya,
    StageGirlAkira,
    StageGirlAruru,
    StageGirlClaudine,
    StageGirlFumi,
    StageGirlFutaba,
    StageGirlHikari,
    StageGirlHisame,
    StageGirlIchie,
    StageGirlJunna,
    StageGirlKaoruko,
    StageGirlKaren,
    StageGirlKoharu,
    StageGirlLalafin,
    StageGirlMahiru,
    StageGirlMaya,
    StageGirlMeiFan,
    StageGirlMichiru,
    StageGirlMisora,
    StageGirlNana,
    StageGirlRui,
    StageGirlShiori,
    StageGirlShizuha,
    StageGirlSuzu,
    StageGirlTamao,
    StageGirlTsukasa,
    StageGirlYachiyo,
    StageGirlYuyuko,
    StrengthFutaba,
    SunIchie,
    TemperanceFumi,
    TowerHikari,
    WarriorMaya,
    WheelOfFortuneKaren,
    WhiteFrontierAruru,
    WorldMaya,
    WukongMaya,
    YellowTsukasa,
    YorimitsuYachiyo,
).associateBy { it.name }
