package xyz.qwewqa.relive.simulator.core.presets.memoir

val memoirs = listOf(
    UnshakableFeelings,
    FriendsAtTheAquarium,
    UrashimaTaroPerformanceFlyer,
    CoStarringWithHatsuneMiku,
    FirstAnnivSiegfeldInstituteOfMusic,
    FirstAnnivSiegfeldInstituteOfMusicLv1,
    BandsmansGreeting,
    CrazyMadScientist,
    ThePhantomAndChristine,
    PoolsideIncident,
    MerryChristmas2019,
    PrinceAndPrincessEtude,
    SunsetLabMemBadge,
    ReminiscenceMelody,
    ReminiscenceMelodyLv60,
    KappoTomoyesPosterGirl,
    KappoTomoyesPosterGirlLv60,
    UnburnedFlowerUnwitheredFlame,
    XIIHangedManReverse,
    XIIHangedManReverseLv65,
    VILoversReverse,
    VILoversReverseLv65,
    XVITowerUpright,
    XVITowerUprightLv65,
).sortedBy { it.name }.sortedBy { it.cutinData == null }.associateBy { it.name }
